src/AppBundle/Entity/Team.php
<?php

namespace AppBundle\Entity;

use AppBundle\Entity\Comment\TeamComment;
use AppBundle\Enum\TeamAccessType;
use AppBundle\Enum\TeamUserStatus;
use AppBundle\Util\FileUtil;
use Doctrine\Common\Collections\ArrayCollection;
use Doctrine\Common\Collections\Collection;
use Doctrine\ORM\Mapping as ORM;
use Gedmo\Timestampable\Traits\TimestampableEntity;
use Symfony\Component\HttpFoundation\File\UploadedFile;
use Symfony\Component\Validator\Constraints as Assert;
use JMS\Serializer\Annotation as JMS;

/**
 * Team
 *
 * @ORM\Table(name="team")
 * @ORM\Entity(repositoryClass="AppBundle\Repository\TeamRepository")
 * @ORM\HasLifecycleCallbacks
 * @JMS\ExclusionPolicy("NONE")
 *
 */
class Team
{
    use TimestampableEntity;

    /**
     * @var int
     *
     * @ORM\Column(name="id", type="integer")
     * @ORM\Id
     * @ORM\GeneratedValue(strategy="AUTO")
     * @JMS\Groups({"Update", "Show", "List"})
     */
    protected $id;

    /**
     * Title
     *
     * @var string
     * @Assert\NotBlank()
     * @JMS\Groups({"Create", "Update", "Show", "List"})
     * @ORM\Column(type="string", length=255, nullable=false)
     */
    protected $title;

    /**
     * Mission
     *
     * @var string
     * @Assert\NotBlank()
     * @JMS\Groups({"Create", "Update", "Show"})
     * @ORM\Column(type="string", length=255, nullable=false)
     */
    protected $mission;

    /**
     * Description
     *
     * @var string
     * @Assert\NotBlank()
     * @JMS\Groups({"Create", "Update", "Show", "List"})
     * @ORM\Column(type="string", length=255, nullable=true)
     */
    protected $description;

    /**
     * @var Collection
     *
     * @JMS\Groups({"Show", "Create", "Update"})
     * @ORM\OneToMany(targetEntity="AppBundle\Entity\TeamUser", mappedBy="team", cascade={"persist"}, fetch="EXTRA_LAZY")
     */
    protected $teamUsers;
    
    /**
     * @var User
     *
     * @JMS\Groups({"Show", "List"})
     * @Assert\NotBlank()
     * @ORM\ManyToOne(targetEntity="AppBundle\Entity\User")
     * @ORM\JoinColumns({
     *   @ORM\JoinColumn(name="admin_id", referencedColumnName="id", nullable=false)
     * })
     */
    protected $admin;

    /**
     * @var Collection
     *
     * @JMS\Groups({"Show", "Update"})
     * @ORM\ManyToMany(targetEntity="AppBundle\Entity\Project", inversedBy="teams", fetch="EXTRA_LAZY")
     * @ORM\JoinTable(name="team_projects")
     */
    protected $projects;

    /**
     * @var Collection
     *
     * @JMS\Groups({"Show", "Create", "Update"})
     * @ORM\OneToMany(targetEntity="AppBundle\Entity\Image\TeamImage", mappedBy="team", cascade={"persist"}, fetch="EXTRA_LAZY")
     */
    protected $images;

    /**
     * Access Type
     *
     * @var int
     * @Assert\Choice(callback = {"AppBundle\Enum\TeamAccessType", "getChoices"}, message="Enter a valid access type.")
     * @JMS\Groups({"create", "Update", "Show", "List"})
     * @ORM\Column(type="integer", nullable=false)
     * @see TeamAccessType
     */
    protected $accessType = TeamAccessType::PRIVATE_ACCESS;

    /**
     * @var UploadedFile
     * @JMS\Exclude
     */
    protected $imageTemp;

    /**
     * @var UploadedFile
     * @JMS\Exclude
     * @Assert\File(
     *     maxSize = "5M",
     *     mimeTypes = {"image/jpeg", "image/gif", "image/png", "image/tiff"},
     *     maxSizeMessage = "The maxmimum allowed file size is 5MB.",
     *     mimeTypesMessage = "Only the filetypes image are allowed."
     * )
     */
    protected $imageFile;

    /**
     * @var string
     * @ORM\Column(type="string", length=255, nullable=true, name="image_path")
     * @JMS\Exclude
     */
    protected $imagePath;

    /**
     * @var UploadedFile
     * @JMS\Exclude
     */
    protected $coverImageTemp;

    /**
     * @var UploadedFile
     * @JMS\Exclude
     * @Assert\File(
     *     maxSize = "5M",
     *     mimeTypes = {"image/jpeg", "image/gif", "image/png", "image/tiff"},
     *     maxSizeMessage = "The maxmimum allowed file size is 5MB.",
     *     mimeTypesMessage = "Only the filetypes image are allowed."
     * )
     */
    protected $coverImageFile;

    /**
     * @ORM\Column(type="string", length=255, nullable=true, name="cover_image_path")
     * @JMS\Exclude
     */
    protected $coverImagePath;

    /**
     * @var Collection
     *
     * @ORM\OneToMany(targetEntity="AppBundle\Entity\Comment\TeamComment", mappedBy="team", cascade={"persist"}, fetch="EXTRA_LAZY")
     * @ORM\OrderBy({"createdAt" = "DESC"})
     * @JMS\Groups({"Show", "List"})
     * @JMS\Exclude
     */
    protected $comments;

    /**
     * Constructor
     */
    public function __construct()
    {
        $this->teamUsers  = new ArrayCollection();
        $this->projects   = new ArrayCollection();
        $this->images = new ArrayCollection();
        $this->comments = new ArrayCollection();
    }

    /**
     * Get id
     *
     * @return int
     */
    public function getId()
    {
        return $this->id;
    }

    public function getImageAbsolutePath()
    {
        return $this->imagePath ? $this->getImageUploadRootDir().'/'.$this->imagePath : null;
    }

    /**
     * Image Web path
     *
     * @JMS\VirtualProperty
     * @JMS\Groups({"Update", "Show", "List", "Create"})
     * @JMS\Type("string")
     * @return null|string
     */
    public function getImageWebPath()
    {
        if ($this->imagePath && is_file($this->getImageAbsolutePath())) {
            return $this->getImageUploadDir().'/'.$this->imagePath;
        }

        return null;
    }

    protected function getImageUploadRootDir()
    {
        // the absolute directory path where uploaded
        // documents should be saved
        return __DIR__.'/../../../web/'.$this->getImageUploadDir();
    }

    protected function getImageUploadDir()
    {
        // get rid of the __DIR__ so it doesn't screw up
        // when displaying uploaded doc/image in the view.
        return 'uploads/teams';
    }

    /**
     * Sets image file.
     *
     * @param UploadedFile $file
     */
    public function setImageFile(UploadedFile $file = null)
    {
        $this->imageFile = $file;

        // check if we have an old image path
        if (is_file($this->getImageAbsolutePath())) {
            // store the old name to delete after the update
            $this->imageTemp = $this->getImageAbsolutePath();
        }

        $this->preUploadImage();
    }

    /**
     * Get image file.
     *
     * @return UploadedFile
     */
    public function getImageFile()
    {
        return $this->imageFile;
    }

    public function preUploadImage()
    {
        if (null !== $this->getImageFile()) {
            $this->imagePath = FileUtil::generateFilename($this->getImageFile());
        }
    }

    /**
     * @ORM\PostPersist
     * @ORM\PostUpdate
     */
    public function uploadImage()
    {
        if (null === $this->getImageFile()) {
            return;
        }

        // check if we have an old image
        if (isset($this->imageTemp)) {
            // delete the old image
            unlink($this->imageTemp);
            // clear the temp image path
            $this->imageTemp = null;
        }

        // you must throw an exception here if the file cannot be moved
        // so that the entity is not persisted to the database
        // which the UploadedFile move() method does
        $this->getImageFile()->move(
            $this->getImageUploadRootDir(),
            $this->imagePath
        );

        $this->setImageFile(null);
    }

    /**
     * @ORM\PreRemove
     */
    public function storeImageFilenameForRemove()
    {
        $this->imageTemp = $this->getImageAbsolutePath();
    }

    /**
     * @ORM\PostRemove
     */
    public function removeImageUpload()
    {
        if (isset($this->imageTemp)) {
            unlink($this->imageTemp);
        }
    }

    /**
     * Set imagePath
     *
     * @param string $imagePath
     * @return $this
     */
    public function setImagePath($imagePath)
    {
        $this->imagePath = $imagePath;

        return $this;
    }

    /**
     * Get imagePath
     *
     * @return string
     */
    public function getImagePath()
    {
        return $this->imagePath;
    }

    public function getCoverImageAbsolutePath()
    {
        return $this->coverImagePath ? $this->getImageUploadRootDir().'/'.$this->coverImagePath : null;
    }

    /**
     * Cover Image Web path
     *
     * @JMS\VirtualProperty
     * @JMS\Groups({"Create", "Update", "Show", "List"})
     * @JMS\Type("string")
     * @return null|string
     */
    public function getCoverImageWebPath()
    {
        if ($this->coverImagePath && is_file($this->getImageAbsolutePath())) {
            return $this->getImageUploadDir().'/'.$this->coverImagePath;
        }

        return null;
    }

    /**
     * Sets cover image file.
     *
     * @param UploadedFile $file
     */
    public function setCoverImageFile(UploadedFile $file = null)
    {
        $this->coverImageFile = $file;

        // check if we have an old image path
        if (is_file($this->getCoverImageAbsolutePath())) {
            // store the old name to delete after the update
            $this->coverImageTemp = $this->getCoverImageAbsolutePath();
        }

        $this->preUploadCoverImage();
    }

    /**
     * Get cover image file.
     *
     * @return UploadedFile
     */
    public function getCoverImageFile()
    {
        return $this->coverImageFile;
    }

    public function preUploadCoverImage()
    {
        if (null !== $this->getCoverImageFile()) {
            $this->coverImagePath = FileUtil::generateFilename($this->getCoverImageFile());
        }
    }

    /**
     * @ORM\PostPersist
     * @ORM\PostUpdate
     */
    public function uploadCoverImage()
    {
        if (null === $this->getCoverImageFile()) {
            return;
        }

        // check if we have an old image
        if (isset($this->coverImageTemp)) {

src/AppBundle/Resources/views/Material/list_application_types.html.twig
{% extends 'SonataAdminBundle:CRUD:list_choice.html.twig' %}
{% block field %}
    {% for type in object.applicationTypes %}
        {{ staticCall('AppBundle\\Enum\\ApplicationType', 'getTitle', {key: type}) }}{% if not loop.last %}, {% endif %}
    {% endfor %}
{% endblock %}

src/AppBundle/Resources/views/Material/list_material_shape.html.twig
{% extends 'SonataAdminBundle:CRUD:base_list_field.html.twig' %}
{% block field %}
    <a href="{{ admin.generateCustomUrl('edit', object.materialShapeSize.materialShape, {}, true) }}">
        {{ value }}
    </a>
{% endblock %}

src/AppBundle/Resources/views/Material/list_material_type.html.twig
{% extends 'SonataAdminBundle:CRUD:base_list_field.html.twig' %}
{% block field %}
    {% if object.materialType %}
        <a href="{{ admin.generateCustomUrl('edit', object.materialType, {}, true) }}">
            {{ value }}
        </a>
    {% endif %}
{% endblock %}

src/AppBundle/Resources/views/Material/list_object3d.html.twig
{% extends 'SonataAdminBundle:CRUD:base_list_field.html.twig' %}
{% block field %}
    {% if object.object3d %}
        <a href="{{ admin.generateCustomUrl('edit', object.object3d, {}, true) }}">
            {{ value }}
        </a>
        {% if object.object3d.imageWebPath != null %}
            <br>
            <img src="{{ image(object.object3d.imageWebPath).resize(124,124) }}">
        {% endif %}
    {% endif %}
{% endblock %}

src/AppBundle/Resources/views/Material/list_popup_image.html.twig
{% extends 'SonataAdminBundle:CRUD:base_list_field.html.twig' %}
{% block field %}
    <div>
        {% if object.popupImagePath != null %}
            <img src="{{ image(object.popupImageWebPath).resize(124,124) }}">
        {% else %}
            <span>No picture</span>
        {% endif %}
    </div>
{% endblock %}

src/AppBundle/Resources/views/Material/list_product_type.html.twig
{% extends 'SonataAdminBundle:CRUD:base_list_field.html.twig' %}
{% block field %}
    <a href="{{ admin.generateCustomUrl('edit', object.productType, {}, true) }}">
        {{ value }}
    </a>
    {% if object.productType.imageWebPath != null %}
        <br>
        <img src="{{ image(object.productType.imageWebPath).resize(124,124) }}">
    {% endif %}
{% endblock %}

src/AppBundle/Resources/views/Material/list_size.html.twig
{% extends 'SonataAdminBundle:CRUD:base_list_field.html.twig' %}
{% block field %}
    <a href="{{ admin.generateCustomUrl('edit', object.materialShapeSize, {}, true) }}">
        {{ value }}
    </a>
    {% if object.materialShapeSize.imageWebPath != null %}
        <br>
        <img width="124" src="{{ asset(object.materialShapeSize.imageWebPath) }}">
    {% endif %}
{% endblock %}